---
# CNPG Secret for admin_service role
# Password will be base64 encoded by CNPG when it creates the role
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-admin-service
  namespace: saasodoo
  labels:
    app.kubernetes.io/name: admin-service
    app.kubernetes.io/component: database
type: kubernetes.io/basic-auth
stringData:
  username: admin_service
  password: "CHANGE_ME_admin_service_password_12345"  # Change this!
