---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: saasodoo
  labels:
    app.kubernetes.io/name: mailhog
    app.kubernetes.io/component: development-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mailhog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mailhog
        app.kubernetes.io/component: development-tool
    spec:
      containers:
        - name: mailhog
          image: mailhog/mailhog:latest
          ports:
            - containerPort: 1025
              name: smtp
              protocol: TCP
            - containerPort: 8025
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
