---
# Notification Service IngressRoute
# Accessible at: http://notification.109.199.108.243.nip.io
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: notification-service
  namespace: saasodoo
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: networking
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`notification.109.199.108.243.nip.io`)
      kind: Rule
      services:
        - name: notification-service
          port: 5000
      middlewares:
        - name: api-ratelimit
