---
apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
  namespace: saasodoo
  labels:
    app.kubernetes.io/name: mailhog
    app.kubernetes.io/component: development-tool
spec:
  type: ClusterIP
  ports:
    - port: 1025
      targetPort: 1025
      protocol: TCP
      name: smtp
    - port: 8025
      targetPort: 8025
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mailhog
