---
# MailHog IngressRoute
# Accessible at: http://mail.109.199.108.243.nip.io
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mailhog
  namespace: saasodoo
  labels:
    app.kubernetes.io/name: mailhog
    app.kubernetes.io/component: networking
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`mail.109.199.108.243.nip.io`)
      kind: Rule
      services:
        - name: mailhog-service
          port: 8025
