---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kaui
  namespace: saasodoo
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`billing-admin.109.199.108.243.nip.io`)
      kind: Rule
      services:
        - name: kaui
          port: 8080
