---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: killbill
  namespace: saasodoo
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`billing.109.199.108.243.nip.io`)
      kind: Rule
      services:
        - name: killbill
          port: 8080
